---
- hosts: airflow
  remote_user: ubuntu
  
  tasks:
        
    - name: Install pip
      become: yes
      ansible.builtin.apt:
        name: python3-pip 
        update_cache: true
    
    - name: Copy AirflowInstall.sh
      ansible.builtin.copy:
        src: ./AirflowInstall.sh
        dest: ./AirflowInstall.sh
        mode: u+x

    - name: Install Airflow
      become: yes
      ansible.builtin.shell:
        cmd: ./AirflowInstall.sh