---
- hosts: clickhouse
  remote_user: ubuntu
  become: yes

  tasks:

    - name: Install soft
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - dirmngr
        update_cache: yes
    
    - name: Add key
      ansible.builtin.apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 8919F6BD2B48D754

    - name: Add Repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.clickhouse.com/deb stable main
    
    - name: Install ClickHouse
      ansible.builtin.apt:
        name:
          - clickhouse-server
          - clickhouse-client
    
    - name: Config ClickHouse
      ansible.builtin.copy:
        src: ./config.xml
        dest: /etc/clickhouse-server/config.d/config.xml

    - name: Restart ClickHouse
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
