---
- hosts: redash
  remote_user: ubuntu
  
  tasks:
          
    - name: Copy RedashInstall.sh
      ansible.builtin.copy:
        src: ./RedashInstall.sh
        dest: ./RedashInstall.sh
        mode: u+x

    - name: Install Redash
      become: yes
      ansible.builtin.shell:
        cmd: ./RedashInstall.sh